import type { Metadata } from "next";
import { Staatliches as Staat } from "next/font/google";
import "../globals.css";

import { cn } from "@/lib/utils"

const font_staat = Staat({
  subsets: ['latin'],
  variable: "--font-sans",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
      >
        {children}
      </body>
    </html>
  );
}
